# Generated by Django 4.0.2 on 2022-02-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Operations",
            new_name="Operation",
        ),
        migrations.AlterModelOptions(
            name="operation",
            options={
                "verbose_name": "Operation",
                "verbose_name_plural": "Operations",
            },
        ),
    ]
